main: com.cavetale.pluginfo.PlugInfoPlugin

name: PlugInfo
version: 0.1
description: Plugin Information Lookup
api-version: '1.21.8'

author: StarTux
website: https://github.com/StarTux/PlugInfo

depend: []
softdepend: [PlugManX]

commands:

  pluginfo:
    permission: pluginfo.pluginfo
    aliases: [pluginfo]
    usage: |-
      /pluginfo list
      /pluginfo dump <plugin>
      /pluginfo depend <plugin>
      /pluginfo author <name>
      /pluginfo nauthor <name>
      /pluginfo listen <event>
      /pluginfo permission <permission>
      /pluginfo command <cmd>
      /pluginfo reload <plugin>
      /pluginfo unload <plugin>
      /pluginfo graph

permissions:

  pluginfo.pluginfo:
    description: Use /pluginfo
    default: op
